all: part0 part1 part2 part3

part0: smsh.h smsh1.c splitline.c execute.c
	gcc -o smsh1 smsh1.c splitline.c execute.c

part1: smsh2.h smsh2.c splitline2.c execute2.c
	gcc -o smsh2 smsh2.c splitline2.c execute2.c

part2: smsh3.h smsh3.c splitline3.c execute3.c
	gcc -o smsh3 smsh3.c splitline3.c execute3.c

part3: smsh4.h smsh4.c splitline4.c execute4.c
	gcc -o smsh4 smsh4.c splitline4.c execute4.c