#!/bin/bash
for i in $(seq 1 25)
do
  echo "Shift $i"
  while read -r line
  do

    var=`./create_pattern -n $i -u`
    
    echo  $line|tr '[A-Z]' $var  #use pipe input text to tr to use caesar cipher upper case
    done < $1
done
